<a href="https://colab.research.google.com/github/jiho01/Self-driving_AI/blob/main/0702_Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
#Numpy 가져와 np로 별
import numpy as np

#버전 확인
print(np.__version__)

2.0.2


#Array Class

In [22]:
class Arr:

  @staticmethod
  def arr1():
    arr = np.array([1, 2, 3, 4, 5, 6])
    print(f"\n1차원 배열 : {arr}")

    return arr.copy()

  @staticmethod
  def arr2():
    arr = np.array([[1,2,3],[4,5,6]])
    print(f"\n2차원 배열 : \n{arr}")

    return arr.copy()

  @staticmethod
  def arr3():
    arr = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
    print(f"\n3차원 배열 : \n{arr}")

    return arr.copy()

  @staticmethod
  def arr5():
    arr = np.array([1,2,3,4], ndmin=5)
    print(f"\n다차원 배열 확인 : \n{arr}")

    return arr.copy()

#Numpy Array

In [23]:
#Numpy 배열 객체 ndarry함수 생성

#0차원 배열
arr0 = np.array(42)
print(f"0차원 배열 : {arr0}")

#1차원 배열
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(f"\n1차원 배열 : \n{arr1}")

#2차원 배열
arr2 = np.array([[1,2,3],[4,5,6]])
print(f"\n2차원 배열 : \n{arr2}")

#3차원 배열
arr3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(f"\n3차원 배열 : \n{arr3}")

#고차원 배열
arr5 = np.array([1,2,3,4], ndmin=5)
print(f"\n다차원 배열 확인 : \n{arr5}")

#배열 차원 수 확인
print(f"\n배열 차원 수 확인 : {arr5.ndim}")

#타입 확인
print(f"배열 타입 확인 : {type(arr5)}")


0차원 배열 : 42

1차원 배열 : 
[1 2 3 4 5 6]

2차원 배열 : 
[[1 2 3]
 [4 5 6]]

3차원 배열 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

다차원 배열 확인 : 
[[[[[1 2 3 4]]]]]

배열 차원 수 확인 : 5
배열 타입 확인 : <class 'numpy.ndarray'>


#Array Indexing

In [24]:
#배열 인덱싱

#1차원 배열
arr = Arr.arr1()

print(f"첫 번째 요소 : {arr[0]}")

print(f"세 번째와 네 번째 요소 더하기 : {arr[2] + arr[3]}")


#2차원 배열
arr = Arr.arr2()

print(f"첫 번째 행의 두번 째 열 요소 : {arr[0, 1]}")


#3차원 배열
arr = Arr.arr3()
print(f"첫 번째 행의 두 번째 열의 세 번째 요소 : {arr[0, 1, 2]}")

#음수 인덱싱
print(f"두 번째 행의 마지막 요소 : {arr[1, -1]}")



1차원 배열 : [1 2 3 4 5 6]
첫 번째 요소 : 1
세 번째와 네 번째 요소 더하기 : 7

2차원 배열 : 
[[1 2 3]
 [4 5 6]]
첫 번째 행의 두번 째 열 요소 : 2

3차원 배열 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
첫 번째 행의 두 번째 열의 세 번째 요소 : 6
두 번째 행의 마지막 요소 : [10 11 12]


#Array Slicing

In [25]:
#배열 슬라이싱

#1차원 배열
arr = Arr.arr1()

print(f"1번 ~ 4번 까지 슬라이싱 : {arr[0:4]}")

print(f"5번 ~ 끝 까지 슬라이싱 : {arr[4:]}")

print(f"처음 ~ 3번 까지 슬라이싱 : {arr[:4]}")

#네거티브 슬라이싱
print(f"뒤에서 3번 ~ 맨 뒤에서 1번째 까지 슬라이싱 : {arr[-3:-1]}")

#단계
print(f"2번 ~ 5번 까지 2의 배수로 슬라이싱 : {arr[1:6:2]}")

print(f"처음 ~ 끝 까지 2의 배수로 슬라이싱 : {arr[::2]}")


#2차원
arr = Arr.arr2()

print(f"1번 행 -  2번 ~ 4번까지 슬라이싱 : {arr[0, 1:4]}")

print(f"1번 ~ 2번 행 - 3번 요소 슬라이싱 : {arr[0:2, 2]}")
print(f"1번 ~ 2번 행 - 2번 ~ 4번 요소 슬라이싱 : \n{arr[0:2, 1:4]}")


1차원 배열 : [1 2 3 4 5 6]
1번 ~ 4번 까지 슬라이싱 : [1 2 3 4]
5번 ~ 끝 까지 슬라이싱 : [5 6]
처음 ~ 3번 까지 슬라이싱 : [1 2 3 4]
뒤에서 3번 ~ 맨 뒤에서 1번째 까지 슬라이싱 : [4 5]
2번 ~ 5번 까지 2의 배수로 슬라이싱 : [2 4 6]
처음 ~ 끝 까지 2의 배수로 슬라이싱 : [1 3 5]

2차원 배열 : 
[[1 2 3]
 [4 5 6]]
1번 행 -  2번 ~ 4번까지 슬라이싱 : [2 3]
1번 ~ 2번 행 - 3번 요소 슬라이싱 : [3 6]
1번 ~ 2번 행 - 2번 ~ 4번 요소 슬라이싱 : 
[[2 3]
 [5 6]]


#Array Data Types


---
**파이썬의 데이터 유형**



*   strings- 텍스트 데이터를 나타내는 데 사용되며 텍스트는 따옴표로 묶여 표시됩니다. 예: "ABCD"
* integer- 정수를 나타내는 데 사용됩니다. 예: -1, -2, -3
* float- 실수를 나타내는 데 사용됩니다. 예: 1.2, 42.42
* boolean- 참(True) 또는 거짓(False)을 나타내는 데 사용됩니다.
* complex- 복소수를 나타내는 데 사용됩니다. 예: 1.0 + 2.0j, 1.5 + 2.5j


---


**Numpy의 데이터 유형***

| 코드 | 설명                                   | 예시 dtype           | 비고                                   |
| ---- | -------------------------------------- | -------------------- | -------------------------------------- |
| `i`  | 부호 있는 정수 (integer)               | `int8`, `int32`      | 음수와 양수를 모두 표현할 수 있는 정수 |
| `b`  | 불리언 (boolean)                       | `bool_`              | `True`/`False`                         |
| `u`  | 부호 없는 정수 (unsigned integer)      | `uint8`, `uint32`    | 0 이상의 정수만 표현                   |
| `f`  | 부동소수점 (float)                     | `float32`, `float64` | 소수점을 포함하는 실수                 |
| `c`  | 복소수 (complex float)                 | `complex64`, `complex128` | 실수부와 허수부로 구성된 복소수      |
| `m`  | 시간 델타 (timedelta)                  | `timedelta64[h]`     | 시간 간격을 나타냄                     |
| `M`  | 날짜/시간 (datetime)                   | `datetime64[D]`      | 특정 날짜나 시간을 나타냄              |
| `O`  | 파이썬 객체 (object)                   | `object`             | 임의의 파이썬 객체                     |
| `S`  | 바이트 문자열 (string)                  | `S10`                | 고정 길이 바이트 문자열 (ASCII)        |
| `U`  | 유니코드 문자열 (unicode string)       | `U10`                | 고정 길이 유니코드 문자열              |
| `V`  | 원시 메모리 블록 (void)                | `V8`                 | 지정한 크기의 원시 메모리              |





In [26]:
#데이터 유형

#1차원 배열
arr = Arr.arr1()
print(f"정수 데이터 유형 : {arr.dtype}")

#문자열 배열
arr = np.array(['apple', 'banana', 'cherry'])
print(f"\n문자열 배열 : {arr}")
print(f"문자열 배열 유형 : {arr.dtype}")

#데이터 유형 정하기
arr = np.array([1, 2, 3, 4], dtype='S')
print(f"\n데이터 유형 정하기 : {arr}")
print(f"데이터 유형 정하기 유형 : {arr.dtype}")

#기본 배열 데이터 변환
newarr = arr.astype('i')

print(f"\n기본 배열 데이터 변환 : {newarr}")
print(f"기본 배열 데이터 변환 유형 : {newarr.dtype}")

#bool 데이터 변환
newarr = arr.astype(bool)

print(f"\n기본 배열 데이터 변환 : {newarr}")
print(f"기본 배열 데이터 변환 유형 : {newarr.dtype}")


1차원 배열 : [1 2 3 4 5 6]
정수 데이터 유형 : int64

문자열 배열 : ['apple' 'banana' 'cherry']
문자열 배열 유형 : <U6

데이터 유형 정하기 : [b'1' b'2' b'3' b'4']
데이터 유형 정하기 유형 : |S1

기본 배열 데이터 변환 : [1 2 3 4]
기본 배열 데이터 변환 유형 : int32

기본 배열 데이터 변환 : [ True  True  True  True]
기본 배열 데이터 변환 유형 : bool


#Array copy / view

In [27]:
#배열 copy

#1차원 배열
arr = Arr.arr1()

#copy : 독자적인 배열 생성
arr = Arr.arr1()
cparr = arr.copy()

#원본 배열 수정
arr[0] = 42
print(f"\n수정 배열 : {arr}")
print(f"배열 copy : {cparr}")


#view : 원본 배열과 연동되는 배열 생성
arr = Arr.arr1()
vwarr = arr.view()

#원본 배열 수정
arr[0] = 42
print(f"\n수정 배열 : {arr}")
print(f"배열 view : {vwarr}")

#view 배열 수정
arr = Arr.arr1()
vwarr = arr.view()

vwarr[0] = 42
print(f"\n원본 배열 : {arr}")
print(f"수정 view : {vwarr}")

#데이터 소유 여부
arr = Arr.arr1()

x = arr.copy()
y = arr.view()

print(f"\ncopy 배열 데이터 소유 : {x.base}")
print(f"view 배열 데이터 소유 : {y.base}")


1차원 배열 : [1 2 3 4 5 6]

1차원 배열 : [1 2 3 4 5 6]

수정 배열 : [42  2  3  4  5  6]
배열 copy : [1 2 3 4 5 6]

1차원 배열 : [1 2 3 4 5 6]

수정 배열 : [42  2  3  4  5  6]
배열 view : [42  2  3  4  5  6]

1차원 배열 : [1 2 3 4 5 6]

원본 배열 : [42  2  3  4  5  6]
수정 view : [42  2  3  4  5  6]

1차원 배열 : [1 2 3 4 5 6]

copy 배열 데이터 소유 : None
view 배열 데이터 소유 : [1 2 3 4 5 6]


#Array shape

In [28]:
#배열 모양

#2차원 배열
arr = Arr.arr2()

print(f"첫 번째 차원에 2개 요소, 2번째 차원에 3개 요소 : {arr.shape}")

#5차원 배열
arr = Arr.arr5()

print(f"5번째 차원에만 4개 요소 : {arr.shape}")



2차원 배열 : 
[[1 2 3]
 [4 5 6]]
첫 번째 차원에 2개 요소, 2번째 차원에 3개 요소 : (2, 3)

다차원 배열 확인 : 
[[[[[1 2 3 4]]]]]
5번째 차원에만 4개 요소 : (1, 1, 1, 1, 4)


#Array Reshape


In [29]:
#배열 재구성

#1차원 배열
arr = Arr.arr1()

#1차원 배열 -> 2차원 배열
newarr = arr.reshape(2, 3)
print(f"\n배열 2차원 3요소로 재구성 : \n{newarr}")

#1차원 배열 -> 3차원 배열
newarr = arr.reshape(1, 3, 2)
print(f"\n배열 3차원 2요소로 재구성 : \n{newarr}")

print(f"\n재구성 후 배열은 view : {arr.reshape(2,3).base}")

#알 수 없는 차원
newarr = arr.reshape(1,2,-1)
print(f"\n'-1'은 자동 정렬 : \n{newarr}")

#배열 평면화
print(f"\n1차원 배열로 재배열 : {newarr.reshape(-1)}")


1차원 배열 : [1 2 3 4 5 6]

배열 2차원 3요소로 재구성 : 
[[1 2 3]
 [4 5 6]]

배열 3차원 2요소로 재구성 : 
[[[1 2]
  [3 4]
  [5 6]]]

재구성 후 배열은 view : [1 2 3 4 5 6]

'-1'은 자동 정렬 : 
[[[1 2 3]
  [4 5 6]]]

1차원 배열로 재배열 : [1 2 3 4 5 6]


#Array Iterating

In [30]:
#배열 반복

#1차원 배열
arr = Arr.arr1()

print('\n1차원 출력 : ')
for x in arr:
  print(x)

#2차원 배열
arr = Arr.arr2()

print("\n2차원 출력 : ")
for x in arr:
  print(x)

print('\n1차원 출력 : ')
for x in arr:
  for y in x:
    print(y)

#3차원 배열
arr = Arr.arr3()

print('\n3차원 출력 : ')
for x in arr:
  print(x)

print("\n1차원 출력 : ")
for x in arr:
  for y in x:
    for z in y:
      print(z)


1차원 배열 : [1 2 3 4 5 6]

1차원 출력 : 
1
2
3
4
5
6

2차원 배열 : 
[[1 2 3]
 [4 5 6]]

2차원 출력 : 
[1 2 3]
[4 5 6]

1차원 출력 : 
1
2
3
4
5
6

3차원 배열 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

3차원 출력 : 
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

1차원 출력 : 
1
2
3
4
5
6
7
8
9
10
11
12


In [31]:
#nditer

#3차원 배열
arr = Arr.arr3()

print('\nncditer을 이용한 1차원 출력 : ')
for x in np.nditer(arr):
  print(x)

#1차원 배열
arr = Arr.arr1()

#데이터 유형 변경 후 출력
print("\n데이터 유형 변경 후 출력 : ")
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

#2차원 배열
arr = Arr.arr2()

#모든 행 2배수 출력
print("\n모든 행 2배수 요소 출력 : ")
for x in np.nditer(arr[:, ::2]):
  print(x)

#1차원 배열
arr = Arr.arr1()

#ndenumerate 사용
print("\nndenumerate 사용 : ")
for idx, x in np.ndenumerate(arr):
  print(f"{idx}번째 : {x}")


3차원 배열 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

ncditer을 이용한 1차원 출력 : 
1
2
3
4
5
6
7
8
9
10
11
12

1차원 배열 : [1 2 3 4 5 6]

데이터 유형 변경 후 출력 : 
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')

2차원 배열 : 
[[1 2 3]
 [4 5 6]]

모든 행 2배수 요소 출력 : 
1
3
4
6

1차원 배열 : [1 2 3 4 5 6]

ndenumerate 사용 : 
(0,)번째 : 1
(1,)번째 : 2
(2,)번째 : 3
(3,)번째 : 4
(4,)번째 : 5
(5,)번째 : 6


# Array Join

In [32]:
#배열 결합

#1차원 배열
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(f"배열1 : {arr1}")
print(f"배열2 : {arr2}")

#1차원 배열 두개 합치기
arr = np.concatenate((arr1, arr2))
print(f"\n1차원 배열 결합 : {arr}")

#스택 결합
arr = np.stack((arr1, arr2), axis=1)
print(f"스택 결합 : \n{arr}")

#행 결합
arr = np.hstack((arr1, arr2))
print(f"행 결합 : \n{arr}")

#열 결합
arr = np.vstack((arr1, arr2))
print(f"열 결합 : \n{arr}")

#깊이 결합
arr = np.dstack((arr1, arr2))
print(f"깊이 결합 : \n{arr}")


#2차원 배열
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(f"\n2차원 배열 결합 : \n{arr}")

배열1 : [1 2 3]
배열2 : [4 5 6]

1차원 배열 결합 : [1 2 3 4 5 6]
스택 결합 : 
[[1 4]
 [2 5]
 [3 6]]
행 결합 : 
[1 2 3 4 5 6]
열 결합 : 
[[1 2 3]
 [4 5 6]]
깊이 결합 : 
[[[1 4]
  [2 5]
  [3 6]]]

2차원 배열 결합 : 
[[1 2 5 6]
 [3 4 7 8]]


#Array Split

In [33]:
#배열 분할

#1차원 배열
arr1 = Arr.arr1()

#3번 분할
newarr = np.array_split(arr1, 3)

print(f"3번 분할 : {newarr}")

#4번 분할
newarr = np.array_split(arr1, 4)

print(f"4번 분할 : {newarr}")

print(f"4번 분할 첫 번째 배열 : {newarr[0]}")
print(f"4번 분할 두 번째 배열 : {newarr[1]}")

#2차원 배열
arr2 = Arr.arr2()

newarr = np.array_split(arr2, 3)

print(f"3번 분할 : \n{newarr}")

#축 분할
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

#열 분할
newarr = np.array_split(arr, 3, axis=1)

print(f"열 분할 : \n{newarr}")

newarr = np.hsplit(arr, 3)

print(newarr)


1차원 배열 : [1 2 3 4 5 6]
3번 분할 : [array([1, 2]), array([3, 4]), array([5, 6])]
4번 분할 : [array([1, 2]), array([3, 4]), array([5]), array([6])]
4번 분할 첫 번째 배열 : [1 2]
4번 분할 두 번째 배열 : [3 4]

2차원 배열 : 
[[1 2 3]
 [4 5 6]]
3번 분할 : 
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]
열 분할 : 
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Array Search


In [34]:
#배열 검색

#1차원 배열
arr = Arr.arr1()

#값이 4인 인덱스
x = np.where(arr == 4)
print(f"값이 4인 위치 : {x}")

#튜플 반환
x = np.where(arr%2 == 0)
print(f"짝수 위치 : {x}")

#순서 정렬 검색
x = np.searchsorted(arr, 3)
print(f"숫자 3은 3번째에 삽입되어야 정렬이 되므로 인덱스 값은 : {x}")

#오른쪽부터 시작
x = np.searchsorted(arr, 3, side='right')
print(f"오른쪽부터 시작 : {x}")

#여러 값
x = np.searchsorted(arr, [2, 4, 6])
print(f"여러 값 : {x}")


1차원 배열 : [1 2 3 4 5 6]
값이 4인 위치 : (array([3]),)
짝수 위치 : (array([1, 3, 5]),)
숫자 3은 3번째에 삽입되어야 정렬이 되므로 인덱스 값은 : 2
오른쪽부터 시작 : 3
여러 값 : [1 3 5]


# Array Sort

In [35]:
#정렬 배열

#1차원 배열
arr = np.array([3, 2, 6, 1, 2])
print(f"1차원 배열 : {arr}")
print(f"배열 정렬 : {np.sort(arr)}")

#2차원 배열
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(f"\n2차원 배열 : \n{arr}")
print(f"배열 정렬 : \n{np.sort(arr)}")

#문자열 배열
arr = np.array(['banana', 'cherry', 'apple'])
print(f"\n문자열 배열 : {arr}")
#알파벳순으로 정렬
print(f"알파벳순으로 정렬 : {np.sort(arr)}")

#부울 배열
arr = np.array([True, False, True])
print(f"\n부울 배열 : {arr}")
print(f"부울 배열 정렬 : {np.sort(arr)}")


1차원 배열 : [3 2 6 1 2]
배열 정렬 : [1 2 2 3 6]

2차원 배열 : 
[[3 2 4]
 [5 0 1]]
배열 정렬 : 
[[2 3 4]
 [0 1 5]]

문자열 배열 : ['banana' 'cherry' 'apple']
알파벳순으로 정렬 : ['apple' 'banana' 'cherry']

부울 배열 : [ True False  True]
부울 배열 정렬 : [False  True  True]


# Array Filter

In [36]:
#배열 필터링

#1차원 배열
arr = Arr.arr1()
#부울 배열
x = [True, False, True, False, True, False]
print(f"부울 배열 : {x}")

#필터링
newarr = arr[x]
print(f"배열 필터링 : {newarr}")

#필터 배열
filter_arr = []

for element in arr:
  if element > 4:
    filter_arr.append(True)
  else:
    filter_arr.append(False)


arr = Arr.arr1()
print(f"4보다 큰 부울 배열 : {filter_arr}")

newarr = arr[filter_arr]

print(f"4보다 큰 값 필터 배열 : {newarr}")

#직업 필터
filter_arr = arr > 3
newarr = arr[filter_arr]
print(f"\n3보다 큰 값 직접필터 배열 : {newarr}")


1차원 배열 : [1 2 3 4 5 6]
부울 배열 : [True, False, True, False, True, False]
배열 필터링 : [1 3 5]

1차원 배열 : [1 2 3 4 5 6]
4보다 큰 부울 배열 : [False, False, False, False, True, True]
4보다 큰 값 필터 배열 : [5 6]

3보다 큰 값 직접필터 배열 : [4 5 6]
